server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      # 开启动态路由 基于服务中心名称
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/query/** # 断言，路径相匹配的进行路由
            #- After=2022-04-08T13:34:30+08:00[Asia/Shanghai]
            #- Before=2022-04-08T13:40:00+08:00[Asia/Shanghai]
            #- Between=2022-04-08T13:38:00+08:00[Asia/Shanghai],2022-04-08T13:39:00+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
           - Path=/payment/create/**
#        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/query/**         # 断言，路径相匹配的进行路由
#
#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/create/**         # 断言，路径相匹配的进行路由

#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          predicates:
#            - Path=/**         # 断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
